import type { CanonicalEndpoint, LimiterMetadata } from '../types/analytics.types';

export const limiterRegistry: Record<CanonicalEndpoint, LimiterMetadata> = {
  '/auth/login': {
    endpoint: '/auth/login',
    limiterName: 'loginLimiter',
    limit: 5,
    max: 5,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'login',
    source: 'quby',
  },
  '/auth/register': {
    endpoint: '/auth/register',
    limiterName: 'registerLimiter',
    limit: 5,
    max: 5,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'register',
    source: 'quby',
  },
  '/auth/reset-password': {
    endpoint: '/auth/reset-password',
    limiterName: 'passwordResetLimiter',
    limit: 5,
    max: 5,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'reset-password',
    source: 'quby',
  },
  '/auth/forgot-password': {
    endpoint: '/auth/forgot-password',
    limiterName: 'forgotPasswordLimiter',
    limit: 5,
    max: 5,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'forgot-password',
    source: 'quby',
  },
  '/payment/order': {
    endpoint: '/payment/order',
    limiterName: 'paymentOrderLimiter',
    limit: 10,
    max: 10,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Sliding Window',
    action: 'payment-order',
    source: 'quby',
  },
  '/payment/verify': {
    endpoint: '/payment/verify',
    limiterName: 'paymentVerifyLimiter',
    limit: 10,
    max: 10,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Sliding Window',
    action: 'payment-verify',
    source: 'quby',
  },
  '/booking/create': {
    endpoint: '/booking/create',
    limiterName: 'bookingLimiter',
    limit: 3,
    max: 3,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Sliding Window',
    action: 'booking-create',
    source: 'quby',
  },
  '/payment/webhook': {
    endpoint: '/payment/webhook',
    limiterName: 'none',
    limit: 0,
    max: 0,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'payment-webhook',
    source: 'quby',
  },
  '/global': {
    endpoint: '/global',
    limiterName: 'globalLimiter',
    limit: 200,
    max: 200,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'global',
    source: 'quby',
  },
  '/unknown': {
    endpoint: '/unknown',
    limiterName: 'defaultLimiter',
    limit: 60,
    max: 60,
    windowMs: 60_000,
    windowLabel: '1m',
    algorithm: 'Fixed Window',
    action: 'unknown',
    source: 'quby',
  },
};

export const protectedLimiterMetadata: LimiterMetadata[] = [
  limiterRegistry['/payment/order'],
  limiterRegistry['/auth/login'],
  limiterRegistry['/booking/create'],
  limiterRegistry['/auth/register'],
  limiterRegistry['/payment/verify'],
  limiterRegistry['/payment/webhook'],
];

export function getLimiterMetadata(endpoint: CanonicalEndpoint): LimiterMetadata {
  return limiterRegistry[endpoint] ?? limiterRegistry['/unknown'];
}
